[build-system]
requires = ["maturin>=1.7"]
build-backend = "maturin"

[project]
name = "Fadex"
version = "0.1.0"
description = "A Powerful WebScraper With Unmatched Performance"
authors = [{name = "Fahad", email = "malikfahadnawaz@gmail.com"}]
license = "MIT"
